### PR TITLE
ELPP-873 Dashboard Future Scheduling: Update scheduling validation

### PR DESCRIPTION
**Pull request by apricot13**

### CODE REVIEW

**Comment by davidcmoulton** [comment]
## Scheduled tab
1. If rescheduling an article results in a failure message, the keyboard tab focus is on the greyed out main page. It should be in the modal, preferably on the Close button.
2. When scheduling a new article, if an invalid time is entered on a future date, the Schedule button is enabled, but clicking it does nothing and the input fields don't have the expected danger colour. I'd expect to see the Schedule button disabled, or a validation failure message.
3. There is a deprecation warning in the console from the moment library. It relates to ways of creating dates, citing https://github.com/moment/moment/issues/1407
4. When trying to cancel an article's scheduled publish, clicking on the Cancel button (I chose article 002273's), brings up the confirmation modal dialogue, but clicking Yes didn't seem to have any effect. (Clicking No dismisses the modal as expected.)
5. Comparing schedule new vs. reschedule behaviour validation appearance: In the modal to schedule a new article, it only indicates invalid fields once one of the fields has received focus, and has then either received input, or has lost focus again. In comparison, the Reschedule article modal indicates invalid fields by default. This is a tiny inconsistency, and there might be a good reason I'm not aware of as to why it's like this. If it's intentional, fine, otherwise I think the behaviour should be consistent.

**Comment by apricot13** [comment]
## Scheduled tab
1. ~~If rescheduling an article results in a failure message, the keyboard tab focus is on the greyed out main page. It should be in the modal, preferably on the Close button.~~
2. ~~When scheduling a new article, if an invalid time is entered on a future date, the Schedule button is enabled, but clicking it does nothing and the input fields don't have the expected danger colour. I'd expect to see the Schedule button disabled, or a validation failure message.~~
   **Possibly related to isScheduledTimeValid in validation method - fixing this will fix the last point too** 
3. ~~There is a deprecation warning in the console from the moment library. It relates to ways of creating dates, citing https://github.com/moment/moment/issues/1407~~
4. ~~When trying to cancel an article's scheduled publish, clicking on the Cancel button (I chose article 002273's), brings up the confirmation modal dialogue, but clicking Yes didn't seem to have any effect. (Clicking No dismisses the modal as expected.)~~
5. ~~Comparing schedule new vs. reschedule behaviour validation appearance: In the modal to schedule a new article, it only indicates invalid fields once one of the fields has received focus, and has then either received input, or has lost focus again. In comparison, the Reschedule article modal indicates invalid fields by default. This is a tiny inconsistency, and there might be a good reason I'm not aware of as to why it's like this. If it's intentional, fine, otherwise I think the behaviour should be consistent.~~

**Comment by apricot13** [comment]
- added time into rescheduling modal
- fields are validated instantly
- schedule button is disable duntil valid

**Comment by davidcmoulton** [comment]
Looks good. Happy for this to be merged.

**Pull request merged**
