### PR TITLE
ELPP-784 ELPP-794 Future Scheduling Front End

### PR DESCRIPTION
**Pull request by apricot13**

### CODE REVIEW

**Comment by davidcmoulton** [comment]
On the modal that pops up when you click on Schedule new article button on the scheduled tab:
- Instructions on what to enter for the article id need to be clearer: the example text suggests to enter the whole example text string with just the final set of digits in bold being variable: "10.7554/elife.**00286**". But entering that doesn't validate.
- Scheduled time input is awkward to use: the time is available to enter as a dropdown minute by minute. This is a very, very long list of possible times. The UXPin has it as a field you can type into, which seems more intuitive.

**Comment by davidcmoulton** [comment]
On the scheduled tab calendar view, no articles are showing (test services are returning what looks like correct json).

**Comment by apricot13** [comment]
@davidcmoulton 

I will remove the help text completely!

The time picker has change now and will also be on two lines (and closer together) when I merge this branch
image

The calendar wasn't showing items because the test_services haven't been updated (and I was working wih the real ones) I will put a fix into the services until they are more fleshed out so they both work

**Comment by davidcmoulton** [comment]
I don't seem able to add line comments, so have put feedback in this conversation, with paths for reference:

There are TODOs querying the need for code in files:
- `source/_src/app/datepicker.js`
- `source/_src/app/dropdowns.js`

Query: do they need addressing as part of this work?

The file at `source/_src/app/archive.js` does nothing but provide existence of object properties (i.e. `app.archive` exists, and has methods `init` and `bindEvents` but they do nothing).

Query: is this required?

There is an id selector `#calendar` in `source/css/scss/generic/_z-index.scss` and in `source/css/scss/objects/_calendar.scss`.

Request: Please can this be changed to a class selector `.calendar`? Let me know if this presents any issues. We really want to avoid high selector specificity.

**Comment by apricot13** [comment]
@davidcmoulton 

re the TODO's I came across those from saads time and wanted to mark them to be removed when I start work on ELPP-825

as discussed I will add a note to say archive.js is a placeholder file

i will update the CSS as part of ELPP-825 :)

**Pull request merged**
